// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * Actions that can be performed.
 * Purely aesthetic; have no actual effect on simulation.
 * (Although the simulation may want to track the 'parents' of
 * particular robots.)
 * Actions may have 'targets', which are the units on which
 * the actions were performed.
 */
public final class Action {
  private Action() { }
  /**
   * Build a unit.
   * Target: spawned unit
   */
  public static final byte SPAWN_UNIT = 7;
  /**
   * Die due to an uncaught exception
   * Target: none
   */
  public static final byte DIE_EXCEPTION = 8;
  /**
   * Die due to suicide.
   * Target: none
   */
  public static final byte DIE_SUICIDE = 9;
  /**
   * Die due to being killed.
   * Target: killer (lumberjack or tank)
   */
  public static final byte DIE_KILLED = 10;
  /**
   * Perform a lumberjack strike.
   * Target: none
   */
  public static final byte LUMBERJACK_STRIKE = 11;

  public static final String[] names = { "FIRE", "FIRE_TRIAD", "FIRE_PENTAD", "CHOP_TREE", "SHAKE_TREE", "PLANT_TREE", "WATER_TREE", "SPAWN_UNIT", "DIE_EXCEPTION", "DIE_SUICIDE", "DIE_KILLED", "LUMBERJACK_STRIKE", };

  public static String name(int e) { return names[e]; }
}

