// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * The possible types of things that can exist.
 * Note that ... are not treated as bodies.
 */
public final class BodyType {
  private BodyType() { }
  /**
   * Archons are the mobile equivalent of a HQ whose sole purpose is to hire
   * gardeners to maintain the land.
   */
  public static final byte ARCHON = 0;
  /**
   * Gardeners are caretakers of the land
   * while also cultivating all other player robots.
   */
  public static final byte GARDENER = 1;
  /**
   * Lumberjacks are melee units equipped for felling.
   */
  public static final byte LUMBERJACK = 2;
  /**
   * Soldiers are all-around units with a tricky shot.
   */
  public static final byte SOLDIER = 3;
  /**
   * Tanks are large, slow units with powerful ...
   */
  public static final byte TANK = 4;
  /**
   * Scouts are fast units that move around without obstruction.
   */
  public static final byte SCOUT = 5;
  /**
   * Delivery drones are slow units that can pick other units up
   */
  public static final byte DELIVERY_DRONE = 6;

  public static final String[] names = { "ARCHON", "GARDENER", "LUMBERJACK", "SOLDIER", "TANK", "SCOUT", "DELIVERY_DRONE", "TREE_BULLET", "TREE_NEUTRAL", "BULLET", "NONE", };

  public static String name(int e) { return names[e]; }
}

